solutions/pcc_3e-main/solution_files/chapter_19/ex_19_1_blog/blog_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blogs.urls')),
]

solutions/pcc_3e-main/solution_files/chapter_19/ex_19_1_blog/blogs/urls.py
"""Defines URL patterns for blogs."""

from django.urls import path

from . import views

app_name = 'blogs'
urlpatterns = [
    # Home page
    path('', views.index, name='index'),
    # Page to view all blogs that have been created.
    path('blogs/', views.blogs, name='blogs'),
    # Page to view an individual blog, and all its posts.
    path('blog/<int:blog_id>/', views.blog, name='blog'),

    # Page for creating a new blog.
    path('new_blog/', views.new_blog, name='new_blog'),
    # Page for writing a new post.
    path('new_post/<int:blog_id>/', views.new_post, name='new_post'),
    # Page for editing an existing post.
    path('edit_post/<int:post_id>/', views.edit_post, name='edit_post'),
]

solutions/pcc_3e-main/solution_files/chapter_19/ex_19_1_blog/blogs/models.py
from django.db import models

class Blog(models.Model):
    """Represents one person or organization's blog."""
    name = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """Return a string representation of the blog."""
        return self.name

class BlogPost(models.Model):
    """Represents an individual post."""
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    
    title = models.CharField(max_length=500)
    body = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """Return a string representing the blog post."""
        if len(self.title) > 50:
            return f"{self.title[:50]}..."
        else:
            return self.title

solutions/pcc_3e-main/solution_files/chapter_19/ex_19_1_blog/blogs/forms.py
from django import forms

from .models import Blog, BlogPost


class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ['name']
        labels = {'name': ''}

class BlogPostForm(forms.ModelForm):
    class Meta:
        model = BlogPost
        fields = ['title', 'body']

        widgets = {'body': forms.Textarea(attrs={'cols': 80})}

solutions/pcc_3e-main/solution_files/chapter_19/ex_19_1_blog/blogs/views.py
from django.shortcuts import render, redirect

from .models import Blog, BlogPost
from .forms import BlogForm, BlogPostForm


def index(request):
    """The home page for Blog."""
    return render(request, 'blogs/index.html')

def blogs(request):
    """Page to view all blogs that have been newd."""
    blogs = Blog.objects.all()
    context = {'blogs': blogs}
    return render(request, 'blogs/blogs.html', context)

def blog(request, blog_id):
    """Page to view an individual blog, and all its posts."""
    blog = Blog.objects.get(id=blog_id)
    posts = blog.blogpost_set.all()

    context = {'blog': blog, 'posts': posts}
    return render(request, 'blogs/blog.html', context)

def new_blog(request):
    """Page to new a new blog."""
    if request.method != 'POST':
        # No data submitted; new a blank form.
        form = BlogForm()
    else:
        # POST data submitted; process data.
        form = BlogForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('blogs:blogs')

    # Display a blank or invalid form.
    context = {'form': form}
    return render(request, 'blogs/new_blog.html', context)

def new_post(request, blog_id):
    """Page to create a new post."""
    blog = Blog.objects.get(id=blog_id)

    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = BlogPostForm()
    else:
        # POST data submitted; process data.
        form = BlogPostForm(data=request.POST)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.blog = blog
            new_post.save()
            return redirect('blogs:blog', blog_id=blog_id)

    # Display a blank or invalid form.
    context = {'blog': blog, 'form': form}
    return render(request, 'blogs/new_post.html', context)

def edit_post(request, post_id):
    """Page to edit an existing post."""
    post = BlogPost.objects.get(id=post_id)
    blog = post.blog

    if request.method != 'POST':
        # Initial request; pre-fill form with the current entry.
        form = BlogPostForm(instance=post)
    else:
        # POST data submitted; process data.
        form = BlogPostForm(instance=post, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('blogs:blog', blog_id=blog.id)

    context = {'post': post, 'blog': blog, 'form': form}
    return render(request, 'blogs/edit_post.html', context)

solutions/pcc_3e-main/solution_files/chapter_19/ex_19_1_blog/blogs/templates/blogs/base.html
<p>
  <a href="{% url 'blogs:index' %}">Blog Host</a> -
  <a href="{% url 'blogs:blogs' %}">All blogs</a>
</p>

{% block content %}{% endblock content %}

solutions/pcc_3e-main/solution_files/chapter_19/ex_19_1_blog/blogs/templates/blogs/blog.html
{% extends 'blogs/base.html' %}

{% block content %}

  <p>Blog: {{ blog.name }}</p>

  <p>Posts:</p>
  <ul>
    {% for post in posts %}
      <li>
        <p>{{ post.date_added|date:'M d, Y H:i' }}</p>
        <p>{{ post.title }}</p>
        <p>{{ post.body|linebreaks }}</p>
        <p><a href="{% url 'blogs:edit_post' post.id %}">Edit post</a></p>
      </li>
    {% empty %}
      <li>This blog does not have any posts yet.</li>
    {% endfor %}
  </ul>

  <a href="{% url 'blogs:new_post' blog.id %}">Create a new post</a>
  
{% endblock content %}

solutions/pcc_3e-main/solution_files/chapter_19/ex_19_1_blog/blogs/templates/blogs/blogs.html
{% extends 'blogs/base.html' %}

{% block content %}

  <p>All Blogs</p>
  <ul>
    {% for blog in blogs %}
      <li>
        <a href="{% url 'blogs:blog' blog.id %}">
          {{ blog.name }}</a>
      </li>
    {% empty %}
      <li>No blogs have been created yet.</li>
    {% endfor %}
  </ul>

  <a href="{% url 'blogs:new_blog' %}">Start a new blog</a>

{% endblock content %}

solutions/pcc_3e-main/solution_files/chapter_19/ex_19_1_blog/blogs/templates/blogs/edit_post.html
{% extends "blogs/base.html" %}

{% block content %}

  <p><a href="{% url 'blogs:blog' blog.id %}">{{ blog.name }}</a></p>

  <p>Edit post:</p>

  <form action="{% url 'blogs:edit_post' post.id %}" method='post'>
    {% csrf_token %}
    {{ form.as_div }}
    <button name="submit">Save changes</button>
  </form>

{% endblock content %}

solutions/pcc_3e-main/solution_files/chapter_19/ex_19_1_blog/blogs/templates/blogs/index.html
{% extends 'blogs/base.html' %}

{% block content %}
  <p>Blog Host lets you create your own blog, and share it with the world.</p>
{% endblock content %}

solutions/pcc_3e-main/solution_files/chapter_19/ex_19_1_blog/blogs/templates/blogs/new_blog.html
{% extends "blogs/base.html" %}

{% block content %}
  <p>Create a new blog:</p>

  <form action="{% url 'blogs:new_blog' %}" method='post'>
    {% csrf_token %}
    {{ form.as_div }}
    <button name="submit">Create blog</button>
  </form>

{% endblock content %}

solutions/pcc_3e-main/solution_files/chapter_19/ex_19_1_blog/blogs/templates/blogs/new_post.html
{% extends "blogs/base.html" %}

{% block content %}

  <p><a href="{% url 'blogs:blog' blog.id %}">{{ blog.title }}</a></p>

  <p>Create a new post:</p>
  <form action="{% url 'blogs:new_post' blog.id %}" method='post'>
    {% csrf_token %}
    {{ form.as_div }}
    <button name='submit'>Create post</button>
  </form>

{% endblock content %}